/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ck_17_18;

import Connect.DataAccessHelper;
import Entity.KhachHang;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author STIREN
 */
public class b extends javax.swing.JFrame{

    /**
     * Creates new form b
     */
    DataAccessHelper d = new DataAccessHelper();
    
    //Lấy mã khách hàng theo tên khách hàng
    public String LayMaKHTheoHoten(String HotenKH)
    {
        String SQL = "SELECT MAKH FROM KHACHHANG WHERE HOTENKH = N'" + HotenKH + "'";
        try {
            d.getConnect();
            Statement st = d.getConn().createStatement();
            ResultSet rs =st.executeQuery(SQL);
            if(rs!=null &&rs.next() )
                return rs.getString("MAKH");
            d.getClose();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }
    
    //Lấy danh sách tên khách hàng
    public ArrayList<KhachHang> LayDSTenKH()
    {
        //String SQL = "SELECT HOTENKH FROM KHACHHANG";
        String SQL = "SELECT * FROM KHACHHANG";
        ArrayList<KhachHang> temp = new ArrayList<KhachHang>();
        try{
            d.getConnect();
            PreparedStatement ps = d.getConn().prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            if(rs!=null)
                while(rs.next()){
                    KhachHang KH = new KhachHang();
                    KH.setMaKH(rs.getString("MAKH"));
                    
                    KH.setHotenKH(rs.getString("HOTENKH"));
                    
                    KH.setDiaChi(rs.getString("DIACHI"));
                    KH.setDienThoai(rs.getString("DIENTHOAI"));
                    temp.add(KH);
                }
            d.getClose();
        }catch(Exception e){
            e.printStackTrace();
        }
        return temp;
    }
   
//    public boolean ThemXe(String SoXe, String HangXe, int NamSX, String MaKH)
//    {
//        String SQL = "INSERT INTO XE VALUES ('" + SoXe + "', N'" + HangXe + "', " + NamSX + ", '" + MaKH + "')" ;
//        try {
//            d.getConnect();
//            Statement st = d.getConn().createStatement();
//            int rs = st.executeUpdate(SQL);
//            if(rs>0)
//                return true;
//            d.getClose();
//        } catch (Exception e) {
//        }
//        return false;
//    }
    
    public b() {
        initComponents();

        for(KhachHang KH: LayDSTenKH())
        {
            cbHotenKH.addItem(KH.getHotenKH());
        }
        
        btnThem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                               
                String SoXe = txfSoXe.getText(); 
                String HangXe = txfHangXe.getText();
                int NamSX = Integer.parseInt(txfNamSX.getText());
                String MaKH = LayMaKHTheoHoten(cbHotenKH.getSelectedItem().toString());
                
                String SQL = "INSERT INTO XE VALUES ('" + SoXe + "', N'" + HangXe + "', " + NamSX + ", '" + MaKH + "')" ;
           
                try {
                    d.getConnect();
                    int st = d.getConn().createStatement().executeUpdate(SQL);
                } catch (SQLException ex) {
                    Logger.getLogger(b.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbHotenKH = new javax.swing.JComboBox<>();
        txfSoXe = new javax.swing.JTextField();
        txfHangXe = new javax.swing.JTextField();
        txfNamSX = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ tên khách hàng");

        jLabel2.setText("Số xe");

        jLabel3.setText("Hãng xe");

        jLabel4.setText("Năm sản xuất");

        btnThem.setText("THÊM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txfSoXe)
                        .addComponent(txfHangXe)
                        .addComponent(cbHotenKH, 0, 204, Short.MAX_VALUE))
                    .addComponent(txfNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbHotenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfNamSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnThem)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b().setVisible(true);
                
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbHotenKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txfHangXe;
    private javax.swing.JTextField txfNamSX;
    private javax.swing.JTextField txfSoXe;
    // End of variables declaration//GEN-END:variables
}
