CREATE DATABASE BaoDuongXe
USE BaoDuongXe
GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(15),
	HOTENKH NVARCHAR(100),
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(10),
	PRIMARY KEY (MAKH)
)
GO 
CREATE TABLE XE
(
	SOXE VARCHAR(15),
	HANGXE NVARCHAR(15),
	NAMSX INT,
	MAKH VARCHAR(15),
	PRIMARY KEY (SOXE)
)


GO
CREATE TABLE BAODUONG
(
	MABD VARCHAR(15),
	NGAYGIONHAN SMALLDATETIME,
	NGAYGIOTRA SMALLDATETIME,
	SOKM INT,
	NOIDUNG NVARCHAR(100),
	SOXE VARCHAR(15),
	PRIMARY KEY (MABD)
)
GO
CREATE TABLE CONGVIEC
(
	MACV VARCHAR(15),
	TENCV NVARCHAR(100),
	DONGIA MONEY,
	PRIMARY KEY (MACV)
)
GO 
CREATE TABLE CT_BD
(
	MABD VARCHAR(15),
	MACV VARCHAR(15),
	PRIMARY KEY (MABD, MACV)
)
GO
ALTER TABLE XE ADD CONSTRAINT XE_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
GO
ALTER TABLE BAODUONG ADD CONSTRAINT BD_XE FOREIGN KEY (SOXE) REFERENCES XE(SOXE)
GO 
ALTER TABLE CT_BD ADD CONSTRAINT CT_BD_BD FOREIGN KEY (MABD) REFERENCES BAODUONG(MABD)
GO 
ALTER TABLE CT_BD ADD CONSTRAINT CT_BD_CV FOREIGN KEY (MACV) REFERENCES CONGVIEC(MACV)
GO
set dateformat dmy
select * from BAODUONG where DATEDIFF(DAY, '21-12-2018', NGAYGIONHAN) = 0

SELECT SUM(DONGIA)
FROM CONGVIEC, BAODUONG, CT_BD
WHERE CONGVIEC.MACV = CT_BD.MACV AND BAODUONG.MABD = CT_BD.MABD AND DATEDIFF(DAY, NGAYGIONHAN, GETDATE()) < 1 AND SOXE = '123' 
GROUP BY SOXE

SELECT TENCV, DONGIA
FROM BAODUONG, CONGVIEC, CT_BD
WHERE BAODUONG.MABD = CT_BD.MABD AND CONGVIEC.MACV = CT_BD.MACV AND DATEDIFF(DAY, NGAYGIONHAN, GETDATE()) = 0 AND SOXE = '123' 

UPDATE BAODUONG
SET NGAYGIOTRA = GETDATE()
WHERE DATEDIFF(DAY, NGAYGIONHAN, GETDATE()) = 0 AND SOXE = '123'

select * from KHACHHANG 
select * from xe
select * from BAODUONG
select * from CT_BD